### ISSUE TITLE
How does one use this with a default gh-pages deploy?

### ISSUE THREAD

**Issue by drvinceknight** [inukshuk/jekyll-scholar#109] opened 2015-10-04 10:56 UTC
I'm not well versed in the use of jekyll plugings. Is this usable as is with a gh-pages deploy?

**Comment by inukshuk** [comment] 2015-10-04 11:17
You can use scholar with gh-pages, but because plugins are not supported out of the box, you need to adjust your workflow. Basically, what you need to do is run jekyll locally and to push the generated site (which is just a static site) to your gh-pages branch. Depending on your workflow and requirements you can automate the process (using git hooks for example) or do it manually every time you want to update your site.

In other words, something like: you work in your master branch as usual. When you want to release your site you change to the gh-pages branch; run jekyll; commit the generated site and push it to GitHub. Alternatively you could set up an commit hook that does this automatically every time you commit to master.

If you google for jekyll plugins and gh-pages I'm sure you will find other options as well.

For context, also see the discussion at #67 #38 and [here](http://stackoverflow.com/questions/21041119/simplest-way-to-get-jekyll-scholar-plugins-on-gh-pages)

**Comment by drvinceknight** [comment] 2015-10-04 11:22
Great thanks: it looks indeed like I'd need to adjust my workflow, I'll
take a look :)

**Comment by reitzig** [comment] 2016-01-11 15:22
@inukshuk I think you can close this; the answer is "no, by design on Github's end". An entry in the README may be a good idea.

**Comment by inukshuk** [comment] 2016-01-12 14:10
PR's welcome :)

**Closed** 2016-01-12 16:55 UTC
