### ISSUE TITLE
Multiple PDF files in repository

### ISSUE THREAD

**Issue by ShadenSmith** [inukshuk/jekyll-scholar#179] opened 2017-01-22 14:01 UTC
Is there a way to link multiple files with the same extension in the repository? The motivation is to serve both the paper and slides for my publications. I have tried distinguishing files named `{{key}}.pdf` and `{{key}}.slides.pdf`, but only the `.pdf` extension is taken, and thus the file `{{key}}.slides` is ignored.

Is it possible to instead match any file starting with `{{key}}.`, and treat the remaining filename as an extension?

**Comment by inukshuk** [comment] 2017-01-23 10:51
I suppose we could do that, yes. In fact, this is likely the correct approach anyway, because IIRC we assume that the file's base name is identical to the key. But the problem is that we do not know the key when we build the repository index, so in order to accomplish this you'd need some kind of truncation symbol (like the dot in your example) which is guaranteed not to be part of a key name. We could use a dot by default (i.e., match up to the first dot and use that part as the key) but which symbol to use should definitely be configurable.

The repository is collected [here](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L361).

**Comment by inukshuk** [comment] 2017-01-24 20:27
OK, I implemented this in a backwards compatible manner (based on this [scholar extras patch](https://git.uwaterloo.ca/caesr-pub/jekyll-scholar/blob/master/patches/issue-179.patch)).

Check out the commit above for a test case; basically, given your example above you can access your files as `links['pdf']` and `links['slides.pdf']`.

**Comment by ShadenSmith** [comment] 2017-01-24 21:08
This is great, thanks a lot!

**Comment by edgemaster** [comment] 2017-01-25 16:46
Oh awesome, I've been meaning to implement this for ages, and have just been bugged by a colleague to implement it now! And I find it's been done already!

**Comment by edgemaster** [comment] 2017-01-25 17:19
Hmm, moving to 5.9 entirely breaks file repository support for me. Debugging now.

**Comment by inukshuk** [comment] 2017-01-25 17:39
Thanks. I was hoping for the change to be backwards compatible as long as the delimiter (a dot by default) does not occur in your bibtex keys (or in one of the folders the repository is nested in) -- if either of that is the case the changes would break the repository.

**Comment by edgemaster** [comment] 2017-01-25 17:41
Aha! The second case might be my issue. I name my site dev directories by their domain names.

**Comment by inukshuk** [comment] 2017-01-25 17:44
Hmm... I suppose we could easily work around this by removing the repository path before matching for the delimiter.

**Comment by edgemaster** [comment] 2017-01-25 17:44
Yep, I'll make and test this change and push it up.

**Comment by edgemaster** [comment] 2017-01-25 19:38
Patched, may I request a release (or my email is grand.edgemaster@gmail.com if you want to add me to the rubygems profile).

**Closed** 2017-01-25 19:37 UTC
Labels: PR welcome

**Comment by inukshuk** [comment] 2017-01-25 19:49
Looks good, thanks!

I added you as a Gem owner, so you can push releases -- I generally try to follow semantic versioning (not always successfully as this issue illustrates). To make a release update the version in `lib/jekyll/scholar/version.rb`, commit, and then follow the steps outlined in the `release` Rake task (either manually or by running it) and you should be good to go!
