### ISSUE TITLE
--suppress_author does not work as expected

### ISSUE THREAD

**Issue by tscholak** [inukshuk/jekyll-scholar#88] opened 2015-06-28 02:47 UTC
Hi,

the `--suppress_author` switch doesn't work as expected if the `csl` file defines a substitution rule for missing author names. For instance, `apa.csl` specifies in the `author-short` macro that an empty `author` name variable is substituted by the `editor` name variable, or, when no editors exist, by the `translator` variable. Finally, if no translator exists, `author` is replaced by the `title` variable. Therefore, instead of `...as Matz explains (2008, p. 42)`, one may get `...as Matz explains ("The Ruby Programming Language", 2008, p. 42)`. I doubt that this is intended behaviour.

Best,
Torsten

**Comment by inukshuk** [comment] 2015-06-29 09:08
@tscholak thanks for reporting. If I read [my own comment](https://github.com/inukshuk/citeproc-ruby/blob/master/lib/citeproc/ruby/renderer/names.rb#L27) this is definitely not the intended behaviour; we'll have to address this in citeproc (I'll open an issue there).

**Comment by inukshuk** [comment] 2016-08-26 11:21
This should be fixed by using `citeproc` 1.0.4 and `citeproc-ruby` 1.1.4 or later.

**Closed by inukshuk** 2016-08-26 11:21 UTC
